CREATE TABLE "Artist"
(
    "ArtistId" INT NOT NULL,
    "Name" VARCHAR(120),
    CONSTRAINT "PK_Artist" PRIMARY KEY  ("ArtistId")
);


INSERT INTO "Artist" ("ArtistId", "Name") VALUES (1, N'AC/DC');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (2, N'Accept');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (3, N'Aerosmith');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (4, N'Alanis Morissette');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (5, N'Alice In Chains');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (6, N'Antônio Carlos Jobim');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (7, N'Apocalyptica');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (8, N'Audioslave');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (9, N'BackBeat');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (10, N'Billy Cobham');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (11, N'Black Label Society');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (12, N'Black Sabbath');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (13, N'Body Count');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (14, N'Bruce Dickinson');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (15, N'Buddy Guy');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (16, N'Caetano Veloso');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (17, N'Chico Buarque');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (18, N'Chico Science & Nação Zumbi');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (19, N'Cidade Negra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (20, N'Cláudio Zoli');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (21, N'Various Artists');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (22, N'Led Zeppelin');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (23, N'Frank Zappa & Captain Beefheart');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (24, N'Marcos Valle');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (25, N'Milton Nascimento & Bebeto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (26, N'Azymuth');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (27, N'Gilberto Gil');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (28, N'João Gilberto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (29, N'Bebel Gilberto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (30, N'Jorge Vercilo');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (31, N'Baby Consuelo');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (32, N'Ney Matogrosso');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (33, N'Luiz Melodia');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (34, N'Nando Reis');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (35, N'Pedro Luís & A Parede');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (36, N'O Rappa');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (37, N'Ed Motta');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (38, N'Banda Black Rio');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (39, N'Fernanda Porto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (40, N'Os Cariocas');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (41, N'Elis Regina');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (42, N'Milton Nascimento');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (43, N'A Cor Do Som');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (44, N'Kid Abelha');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (45, N'Sandra De Sá');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (46, N'Jorge Ben');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (47, N'Hermeto Pascoal');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (48, N'Barão Vermelho');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (49, N'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (50, N'Metallica');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (51, N'Queen');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (52, N'Kiss');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (53, N'Spyro Gyra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (54, N'Green Day');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (55, N'David Coverdale');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (56, N'Gonzaguinha');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (57, N'Os Mutantes');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (58, N'Deep Purple');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (59, N'Santana');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (60, N'Santana Feat. Dave Matthews');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (61, N'Santana Feat. Everlast');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (62, N'Santana Feat. Rob Thomas');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (63, N'Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (64, N'Santana Feat. The Project G&B');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (65, N'Santana Feat. Maná');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (66, N'Santana Feat. Eagle-Eye Cherry');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (67, N'Santana Feat. Eric Clapton');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (68, N'Miles Davis');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (69, N'Gene Krupa');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (70, N'Toquinho & Vinícius');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (71, N'Vinícius De Moraes & Baden Powell');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (72, N'Vinícius De Moraes');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (73, N'Vinícius E Qurteto Em Cy');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (74, N'Vinícius E Odette Lara');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (75, N'Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (76, N'Creedence Clearwater Revival');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (77, N'Cássia Eller');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (78, N'Def Leppard');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (79, N'Dennis Chambers');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (80, N'Djavan');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (81, N'Eric Clapton');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (82, N'Faith No More');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (83, N'Falamansa');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (84, N'Foo Fighters');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (85, N'Frank Sinatra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (86, N'Funk Como Le Gusta');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (87, N'Godsmack');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (88, N'Guns N'' Roses');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (89, N'Incognito');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (90, N'Iron Maiden');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (91, N'James Brown');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (92, N'Jamiroquai');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (93, N'JET');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (94, N'Jimi Hendrix');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (95, N'Joe Satriani');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (96, N'Jota Quest');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (97, N'João Suplicy');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (98, N'Judas Priest');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (99, N'Legião Urbana');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (100, N'Lenny Kravitz');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (101, N'Lulu Santos');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (102, N'Marillion');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (103, N'Marisa Monte');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (104, N'Marvin Gaye');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (105, N'Men At Work');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (106, N'Motörhead');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (107, N'Motörhead & Girlschool');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (108, N'Mônica Marianno');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (109, N'Mötley Crüe');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (110, N'Nirvana');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (111, N'O Terço');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (112, N'Olodum');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (113, N'Os Paralamas Do Sucesso');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (114, N'Ozzy Osbourne');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (115, N'Page & Plant');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (116, N'Passengers');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (117, N'Paul D''Ianno');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (118, N'Pearl Jam');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (119, N'Peter Tosh');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (120, N'Pink Floyd');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (121, N'Planet Hemp');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (122, N'R.E.M. Feat. Kate Pearson');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (123, N'R.E.M. Feat. KRS-One');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (124, N'R.E.M.');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (125, N'Raimundos');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (126, N'Raul Seixas');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (127, N'Red Hot Chili Peppers');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (128, N'Rush');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (129, N'Simply Red');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (130, N'Skank');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (131, N'Smashing Pumpkins');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (132, N'Soundgarden');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (133, N'Stevie Ray Vaughan & Double Trouble');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (134, N'Stone Temple Pilots');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (135, N'System Of A Down');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (136, N'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (137, N'The Black Crowes');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (138, N'The Clash');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (139, N'The Cult');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (140, N'The Doors');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (141, N'The Police');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (142, N'The Rolling Stones');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (143, N'The Tea Party');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (144, N'The Who');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (145, N'Tim Maia');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (146, N'Titãs');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (147, N'Battlestar Galactica');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (148, N'Heroes');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (149, N'Lost');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (150, N'U2');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (151, N'UB40');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (152, N'Van Halen');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (153, N'Velvet Revolver');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (154, N'Whitesnake');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (155, N'Zeca Pagodinho');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (156, N'The Office');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (157, N'Dread Zeppelin');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (158, N'Battlestar Galactica (Classic)');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (159, N'Aquaman');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (160, N'Christina Aguilera featuring BigElf');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (161, N'Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (162, N'Los Lonely Boys');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (163, N'Corinne Bailey Rae');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (164, N'Dhani Harrison & Jakob Dylan');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (165, N'Jackson Browne');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (166, N'Avril Lavigne');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (167, N'Big & Rich');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (168, N'Youssou N''Dour');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (169, N'Black Eyed Peas');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (170, N'Jack Johnson');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (171, N'Ben Harper');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (172, N'Snow Patrol');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (173, N'Matisyahu');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (174, N'The Postal Service');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (175, N'Jaguares');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (176, N'The Flaming Lips');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (177, N'Jack''s Mannequin & Mick Fleetwood');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (178, N'Regina Spektor');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (179, N'Scorpions');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (180, N'House Of Pain');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (181, N'Xis');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (182, N'Nega Gizza');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (183, N'Gustavo & Andres Veiga & Salazar');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (184, N'Rodox');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (185, N'Charlie Brown Jr.');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (186, N'Pedro Luís E A Parede');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (187, N'Los Hermanos');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (188, N'Mundo Livre S/A');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (189, N'Otto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (190, N'Instituto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (191, N'Nação Zumbi');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (192, N'DJ Dolores & Orchestra Santa Massa');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (193, N'Seu Jorge');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (194, N'Sabotage E Instituto');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (195, N'Stereo Maracana');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (196, N'Cake');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (197, N'Aisha Duo');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (198, N'Habib Koité and Bamada');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (199, N'Karsh Kale');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (200, N'The Posies');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (201, N'Luciana Souza/Romero Lubambo');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (202, N'Aaron Goldberg');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (203, N'Nicolaus Esterhazy Sinfonia');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (204, N'Temple of the Dog');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (205, N'Chris Cornell');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (206, N'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (207, N'Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (208, N'English Concert & Trevor Pinnock');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (209, N'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (210, N'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (211, N'Wilhelm Kempff');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (212, N'Yo-Yo Ma');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (213, N'Scholars Baroque Ensemble');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (214, N'Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (215, N'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (216, N'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (217, N'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (218, N'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (219, N'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (220, N'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (221, N'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (222, N'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (223, N'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (224, N'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (225, N'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (226, N'Eugene Ormandy');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (227, N'Luciano Pavarotti');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (228, N'Leonard Bernstein & New York Philharmonic');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (229, N'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (230, N'Aaron Copland & London Symphony Orchestra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (231, N'Ton Koopman');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (232, N'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (233, N'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (234, N'Orchestra of The Age of Enlightenment');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (235, N'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (236, N'James Levine');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (237, N'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (238, N'Maurizio Pollini');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (239, N'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (240, N'Gustav Mahler');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (241, N'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (242, N'Edo de Waart & San Francisco Symphony');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (243, N'Antal Doráti & London Symphony Orchestra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (244, N'Choir Of Westminster Abbey & Simon Preston');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (245, N'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (246, N'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (247, N'The King''s Singers');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (248, N'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (249, N'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (250, N'Christopher O''Riley');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (251, N'Fretwork');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (252, N'Amy Winehouse');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (253, N'Calexico');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (254, N'Otto Klemperer & Philharmonia Orchestra');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (255, N'Yehudi Menuhin');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (256, N'Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (257, N'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (258, N'Les Arts Florissants & William Christie');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (259, N'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (260, N'Adrian Leaper & Doreen de Feis');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (261, N'Roger Norrington, London Classical Players');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (262, N'Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (263, N'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (264, N'Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (265, N'Julian Bream');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (266, N'Martin Roscoe');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (267, N'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (268, N'Itzhak Perlman');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (269, N'Michele Campanella');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (270, N'Gerald Moore');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (271, N'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (272, N'Emerson String Quartet');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (273, N'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (274, N'Nash Ensemble');
INSERT INTO "Artist" ("ArtistId", "Name") VALUES (275, N'Philip Glass Ensemble');