FROM flink:latest
RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.0.1-1.18/flink-sql-connector-kafka-3.0.1-1.18.jar
RUN wget -P /opt/flink/lib  https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-avro/1.18.0/flink-sql-avro-1.18.0.jar
RUN wget -P /opt/flink/lib https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.18.0/flink-sql-avro-confluent-registry-1.18.0.jar

##https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka_2.12/1.19-SNAPSHOT/flink-sql-connector-kafka_scala_2.12-1.19-SNAPSHOT.jar
